server:
  port: 8081

spring:
  application:
    name: sm_db

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sm_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "0724"

  mail:
    host: smtp.qq.com
    port: 587
    username: 366169536@qq.com
    password: ghekyatqgaygbhfh
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
        debug: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      port: 6379
      host: 192.168.10.101
      password: "0724"

mybatis-plus:
  type-aliases-package: com.hmdp.entity

logging:
  level:
    com.hmdp: debug